name: CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Frontend Docker image
      run: docker build -t munday-frontend ./munday-reviews-frontend

    - name: Build Backend Docker image
      run: docker build -t munday-backend ./munday-reviews-backend

    - name: Test Docker Compose
      run: |
        docker-compose -f docker-compose.yml config
        echo "Docker Compose configuration is valid" 