name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Test Backend
      working-directory: ./munday-reviews-backend
      run: |
        npm ci
        npm run lint
        npm test

    - name: Test Frontend
      working-directory: ./munday-reviews-frontend
      run: |
        npm ci
        npm run lint
        npm test -- --watch=false --browsers=ChromeHeadless

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Production
      run: |
        echo "Add your deployment scripts here" 